language: java
jdk:
- oraclejdk7
- oraclejdk8
os:
- linux
branches:
  only:
  - master
  - dev
sudo: required
before_install:
- mvn org.codehaus.mojo:versions-maven-plugin:display-dependency-updates
- mvn org.codehaus.mojo:versions-maven-plugin:display-plugin-updates
after_success:
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN -DcodacyApiBaseUrl=https://api.codacy.com
env:
  global:
  - secure: ZtvZmGCTn8LuMi1ORRxw2nhCIl+zGnCpeOlOecT+MZhb3zlilDZuYSEWzyRekkivWM/6iUrldbkuiGfWq1Uy3nvvGF9fJYkK37Rxm3yQoOUi7kvyE4dVAWgFhofa9yVAmKU6LJFi1h0WRjjn2YFF8MaK8UjjClJt3qEQlmA0dlq0PiWNYk2WGoBbe4uyGe37aSSYz/0b0vIfCfmaFRwAGGrELgJLpJJlAzwG9KMKtO5SXo1K5/LVv6IpgaHVe5M/NdoqJES9FQNlgzV0Cr8pGNALB1a/G52yPQ6bMBdVR4kBZHRZfox7LGsmluNe/l7EwwMTZ8GH5JfoNUXpn0FrKnpInUzizPGTbnj1pLW/vt/9kdKgqVyAvWcWBEhOgUYVNfZcQToptRwPiByn9upWMkM3/no+xpF+mr8ir+vLgk43yJX2HqUPCt1YlM1MaO6OGu29q+PNEJOSVrGAjn/s/LPIyd9Mz1RXp2kF16/ItBp/ynOxViZ+QPoyiKtvkGK8H13Os5KKkQ7cONMfGNStT0g03/9/ssmKhEXPDvicspa7CKqRjGTDONktj7k7tMFmIZv5UZybYnMbf1PvJwAg4N7XXpCA2eTnOaLTIbecF3LnW/JFQ5X1mcGt6dQv9IALEASRm2xVeqNHvp9Hfw/41dHvhO4Ll55q3qe7iKUz54M=
  - secure: OxexJP7eMFpWn47buhe2UIpwLlC+NPV+wzK/C5qhh4G+0MiSS1GE5MqZ/QvcxaJmCuCQvGFZaZ0MX+byhqScTlIjHaPJ99z1E6/p5O1fIRW5PwvgqOVHRpnsVRKrsSUKI/5OS1aQdKxrlnkw8jCm1/XwZCBYmEj+n+EGYYAymX352X8Wl7YGYZehoYuX/vQmmfZB+uBEwoEYtezLwptOchdQF8IxlDccCshGFaiVmA72LzbTraVVAcTikPR1jArJZq2Z4zXeIW4gNjCyuiMXSR0AKR9NecqgZTlLngJQv67Z0wMuKOOpg1RRspeGIYW0MQbl2/eNTPtIW3TeMaOAL/xIa/ngbwSRTxJgFvWUKnCvKq3IfMdyTBJHsEaOCxYHsXdweT0/5IfxtChpK1YovP8/HXks9hK5Rb9S4fN4Bk4yRfPfYP6M1DjnTOxsNIxB+J7miax1qNOggm8lOdDu7OCRD9+YL1uz474ZrGunLoBJNWUMdtRTRFBUJYdiMnj59B7/Njh9p7JGdNCcEAvNBAH+aajFaeSFF+lP//Fh/O6KbG1cAAX/5eZrpIY/aWQZvqnvyIJInzfvc6q7ppo3DIS76LU2Sn3P4Bso1zYPhQ8PAQR1LM+OlO/OVhW6YXpJhINCk++XbEbjptj9O5KCQLbuFppGOuqtwQpKa+iFsDY=
